// Mock analytics data for pharma workflow builder — structured for Runs, Escalations, Audit Trail, CAPA

export const runs = [
    {
        runId: 'RUN-2026-0304-011',
        caseId: 'CASE-EMA-2026-0042',
        conversationId: 'CNV-8Q2H7K',
        created: '2026-03-04T21:42:00Z',
        status: 'Completed',
        documentType: 'CC Form',
        jurisdiction: 'EMA (EU)',
        inputs: 'SOP extraction + policy check',
        outputs: 'Compliant summary generated',
        latency: '2.1s',
        confidence: 94,
        lastModifiedBy: 'j.smith@company.com',
    },
    {
        runId: 'RUN-2026-0304-010',
        caseId: 'CASE-MHRA-2026-0019',
        conversationId: 'CNV-8Q2F4M',
        created: '2026-03-04T20:31:00Z',
        status: 'Pending Review',
        documentType: 'Batch deviation notes',
        jurisdiction: 'MHRA (UK)',
        inputs: 'Batch deviation notes',
        outputs: 'Risk flags: sterility + traceability',
        latency: '3.4s',
        confidence: 62,
        lastModifiedBy: 'system',
    },
    {
        runId: 'RUN-2026-0304-009',
        caseId: 'CASE-FDA-2026-0087',
        conversationId: 'CNV-8Q1Z9D',
        created: '2026-03-04T19:05:00Z',
        status: 'Completed',
        documentType: 'Change control packet',
        jurisdiction: 'FDA (US)',
        inputs: 'Change control packet',
        outputs: 'Audit trail and rationale exported',
        latency: '1.9s',
        confidence: 91,
        lastModifiedBy: 'm.jones@company.com',
    },
    {
        runId: 'RUN-2026-0304-008',
        caseId: null,
        conversationId: 'CNV-8Q1V3P',
        created: '2026-03-04T17:54:00Z',
        status: 'Failed',
        documentType: 'Validation protocol draft',
        jurisdiction: 'EMA (EU)',
        inputs: 'Validation protocol draft',
        outputs: 'Model timeout on attachment parsing',
        latency: '5.8s',
        confidence: null,
        lastModifiedBy: 'system',
    },
    {
        runId: 'RUN-2026-0304-007',
        caseId: 'CASE-EMA-2026-0041',
        conversationId: 'CNV-8Q1T9K',
        created: '2026-03-04T16:22:00Z',
        status: 'Escalated',
        documentType: 'SmPC/PIL',
        jurisdiction: 'EMA (EU)',
        inputs: 'SmPC consistency check',
        outputs: 'Cross-reference mismatch flagged',
        latency: '4.2s',
        confidence: 58,
        lastModifiedBy: 'a.williams@company.com',
    },
    {
        runId: 'RUN-2026-0304-006',
        caseId: 'CASE-MHRA-2026-0018',
        conversationId: 'CNV-8Q1R4L',
        created: '2026-03-04T14:10:00Z',
        status: 'CAPA Open',
        documentType: 'CTD Module',
        jurisdiction: 'MHRA (UK)',
        inputs: 'CTD Module 3.2.P',
        outputs: 'Critical gap: stability data missing',
        latency: '3.1s',
        confidence: 88,
        lastModifiedBy: 'q.audit@company.com',
    },
];

export const escalations = [
    {
        id: 'ESC-001',
        runId: 'RUN-2026-0304-010',
        caseId: 'CASE-MHRA-2026-0019',
        documentType: 'Batch deviation notes',
        reason: 'Low confidence',
        escalatedAt: '2026-03-04T20:31:00Z',
        assignedTo: null,
        status: 'Open',
        overdue: true,
    },
    {
        id: 'ESC-002',
        runId: 'RUN-2026-0304-007',
        caseId: 'CASE-EMA-2026-0041',
        documentType: 'SmPC/PIL',
        reason: 'Risk flag',
        escalatedAt: '2026-03-04T16:25:00Z',
        assignedTo: 'a.williams@company.com',
        status: 'In progress',
        overdue: false,
    },
];

export const auditEvents = [
    {
        id: 'AUD-001',
        actor: 'system',
        action: 'Run started',
        timestamp: '2026-03-04T21:42:00Z',
        entityType: 'Run',
        entityId: 'RUN-2026-0304-011',
        details: 'Workflow triggered via CC Form upload',
        reason: null,
        source: 'CC Form Extraction',
    },
    {
        id: 'AUD-002',
        actor: 'j.smith@company.com',
        action: 'Approved',
        timestamp: '2026-03-04T21:44:12Z',
        entityType: 'Run',
        entityId: 'RUN-2026-0304-011',
        details: 'Auto-approved — confidence 94%',
        reason: 'Within threshold',
        source: 'Review / Approve',
    },
    {
        id: 'AUD-003',
        actor: 'system',
        action: 'Escalated',
        timestamp: '2026-03-04T20:31:00Z',
        entityType: 'Run',
        entityId: 'RUN-2026-0304-010',
        details: 'Confidence below threshold (62%)',
        reason: 'Low confidence',
        source: 'Variation Type Classifier',
    },
    {
        id: 'AUD-004',
        actor: 'a.williams@company.com',
        action: 'Escalated',
        timestamp: '2026-03-04T16:25:00Z',
        entityType: 'Run',
        entityId: 'RUN-2026-0304-007',
        details: 'SmPC cross-reference mismatch',
        reason: 'Risk flag — requires QA review',
        source: 'SmPC Consistency',
    },
    {
        id: 'AUD-005',
        actor: 'q.audit@company.com',
        action: 'CAPA initiated',
        timestamp: '2026-03-04T14:15:00Z',
        entityType: 'Run',
        entityId: 'RUN-2026-0304-006',
        details: 'Critical gap: stability data missing in CTD Module 3.2.P',
        reason: 'Regulatory compliance',
        source: 'Dossier Gap Analysis',
    },
    {
        id: 'AUD-006',
        actor: 'system',
        action: 'Run failed',
        timestamp: '2026-03-04T17:54:00Z',
        entityType: 'Run',
        entityId: 'RUN-2026-0304-008',
        details: 'Model timeout on attachment parsing',
        reason: null,
        source: 'Ask AI',
    },
];

export const capaItems = [
    {
        id: 'CAPA-2026-001',
        runId: 'RUN-2026-0304-006',
        errorDesc: 'Critical gap: stability data missing in CTD Module 3.2.P',
        detectedAt: '2026-03-04T14:10:00Z',
        status: 'Open',
        assignedTo: null,
        dueDate: '2026-03-18',
    },
    {
        id: 'CAPA-2026-002',
        runId: 'RUN-2026-0304-008',
        errorDesc: 'Model timeout on attachment parsing',
        detectedAt: '2026-03-04T17:54:00Z',
        status: 'In progress',
        assignedTo: 'devops@company.com',
        dueDate: '2026-03-11',
    },
];
